<?php

function examples_theme($existing, $type, $theme, $path) {
  $examples = [
    'typography',
    'links',
    'buttons',
    'actions',
    'forms',
    'badges',
    'tags',
    'tables',
    'breadcrumbs',
    'pagination',
    'hero',
    'straps',
    'callouts',
    'features',
    'listings',
    'sections',
    'tabs',
    'accordions',
    'notices',
    'testimonials',
    'cards',
  ];

  $example_templates = array_map(function ($template) {
    return 'examples_' . $template;
  }, $examples);

  $slugs = array_merge(['examples'], $example_templates);

  $templates = [];
  array_walk($slugs, function ($key) use (&$templates) {
    $templates[$key] = [
      'variables' => [
        'example' => ($key !== 'examples' ? $key : NULL),
      ],
    ];
  }, $slugs);

  return $templates;
}
