<?php

/**
 * @file
 * Primary module hooks for Campbell Migrations module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\migrate\MigrateSkipRowException;
use Drupal\migrate\Plugin\MigrateSourceInterface;
use Drupal\migrate\Plugin\MigrationInterface;
use Drupal\migrate\Row;
use Drupal\views\Plugin\views\query\QueryPluginBase;

/**
 * Implements hook_migrate_prepare_row().
 */
function campbell_migrations_migrate_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {

  if ($migration->id() === 'campbell_product_specifications') {
    $attributes_to_include = [
      'ATT539',
      'TradeSizeFractional',
      'ATT424',
      'ATT217',
      'ATT864',
      'ATT797',
      'ATT802',
      'ATT803',
      'ATT805',
      'ATT798',
      'ATT291',
      'TorqueValue',
      'ATT776',
      'ATT345',
      'ATT214',
      'ATT817',
      'ATT858',
      'ATT859',
      'Quik-AlloySlingHooks',
      'Quik-AlloySlingHookwithLatch',
      'ATT205',
      'ATT770',
      'ATT460',
      'ATT457',
      'ATT458',
      'ATT459',
      'ATT777',
      'ATT778',
      'ATT790',
      'ATT789',
      'ATT336',
      'ATT861',
      'ATT804',
      'ATT807',
      'ATT808',
      'ATT809',
      'ATT748',
      'ATT749',
      'ATT750',
      'ATT751',
      'ATT688',
      'ATT774',
      'ATT775',
      'ATT791',
      'ATT758',
      'ATT792',
      'ATT793',
      'ATT810',
      'ATT799',
      'ATT757',
      'ATT800',
      'ATT811',
      'ATT794',
      'ATT795',
      'ATT801',
      'ATT440',
      'ATT395',
      'ATT168',
      'ATT198',
      'ATT274',
      'ATT249',
      'ATT250',
      'ATT545',
      'ATT546',
      'ATT405',
      'ATT447',
      'ATT442',
      'ATT326',
      'ATT923',
      'ATT200',
      'ATT145',
      'ATT425',
      'ATT137',
      'ATT138',
      'ATT315',
      'ATT212',
      'ATT363',
      'ATT364',
      'ATT767',
      'ATT453',
      'ATT288',
      'ATT325',
      'ATT773',
      'ATT362',
      'ATT766',
      'ATT764',
      'ATT143',
      'ATT763',
      'ATT376',
      'ATT147',
      'ATT146',
      'ATT187',
      'ATT786',
      'ATT785',
      'ATT784',
      'ATT783',
      'ATT782',
      'ATT349',
      'ATT335',
      'ATT779',
      'ATT329',
      'ATT400',
      'ATT250',
      'ATT752',
      'ATT908',
      'ATT781',
      'ATT320',
      'ATT780',
      'ATT245',
      'ATT454',
      'ATT753',
      'ATT247',
      'ATT182',
      'ATT745',
      'ATT788',
      'ATT139',
      'ATT140',
      'ATT746',
      'ATT621',
      'ATT330',
      'ATT754',
      'ATT222',
      'ATT225',
      'ATT460',
      'ATT918',
      'ATT327',
      'ATT123',
      'ATT121',
      'ATT286',
      'ATT113',
      'ATT157',
      'ATT937',
      'ATT154',
      'ATT865',
      'ATT857',
      'ATT219',
      'ATT916',
      'ATT917',
      'ATT862',
      'ATT863',
      'ATT867',
      'ATT868',
      'ATT869',
      'ATT870',
      'ATT871',
      'ATT872',
      'ATT873',
      'ATT874',
      'ATT875',
      'ATT853',
      'ATT854',
      'ATT877',
      'ATT878',
      'ATT855',
      'ATT856',
      'ATT806',
      'MUSAICON'
    ];

    if (!in_array($row->getSource()['remote_term_id'], $attributes_to_include)) {
      throw new MigrateSkipRowException('', TRUE);
    }
  }
}

/**
 * Implements hook_views_query_alter().
 */
function campbell_migrations_views_query_alter($view, QueryPluginBase $query) {
  if ($view->id() !== 'taxonomy_menu') {
    return;
  }

  $tableQueue = $query->getTableQueue();
  if (isset($tableQueue['node__field_product_classifications'])) {
    // Only select the first term reference from product_category content.
    $join = &$tableQueue['node__field_product_classifications']['join'];
    $join->extra[] = [
      'field' => 'delta',
      'value' => 0,
      'numeric' => true
    ];
  }
}

/**
 * Implements hook_views_pre_view().
 */
function campbell_migrations_views_pre_view($view, $display_id, &$args) {
  if ($view->id() !== 'taxonomy_menu' || isset($args[0])) {
    return;
  }

  // If no args set and term name is given as default, convert to tid.
  $default = $view->display_handler->display['display_options']['arguments']['term_node_tid_depth']['default_argument_options']['argument'];
  if (!$default || is_numeric($default)) {
    return;
  }

  $term_query = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->getQuery();
  $term = $term_query->condition('name', $default)->execute();
  if (count($term)) {
    $args = [reset($term)];
  }
}
