_core:
  default_config_hash: ttd8HXcqwSjGgp-fWA3gUA8q4TNvXB0a72pkFlnF56g
hotlink: false
origin: 'https://username:password@dev-store.apextoolgroup.com'
origin_dir: sites/ecom/files
use_imagecache_root: true
verify: true
excluded_extensions: ''
