configuration_names:
  0: 'crescenttool_core.settings:warranty_highest_exported_sid'
  2: 'acquia_connector.settings:spi.site_environment'
  4: 'acquia_connector.settings:spi.site_uuid'
  6: 'search_api.server.acquia_search_server:backend_config.connector_config'
