_core:
  default_config_hash: ViXe1Mhsdfc0AY1y-5R7vwxUoVItsnRfbQbQYzQGEEs
api_key: e2ced564867f751a9d66658d01ca426c-us8
api_timeout: 10
cron: false
batch_limit: 100
api_classname: Mailchimp\Mailchimp
test_mode: false
enable_connected: false
connected_id: null
connected_paths: null
webhook_hash: 4ca26d879c3e7638a9b6ef4f1c25f90f
