_core:
  default_config_hash: l58O_yEXSo-SeJi19LXdzTU1tNJG3lmnIhCitRkM1tk
langcode: en
uuid: 9c355964-2f70-4367-987c-a9a4b06c2ec3
name: 'Crescent Australia'
mail: no-reply@crescenttool.com.au
slogan: ''
page:
  403: ''
  404: /node/11327
  front: /node/1
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
