_core:
  default_config_hash: l58O_yEXSo-SeJi19LXdzTU1tNJG3lmnIhCitRkM1tk
langcode: en
uuid: 34cd75f0-7f83-4def-acff-137e76aa0d4e
name: 'Gearwrench Australia'
mail: no-reply@gearwrench.com.au
slogan: ''
page:
  403: ''
  404: /node/22306
  front: /node/1
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
