<?php

/**
 * @file
 * Primary module hooks for Campbell Product Category Filtering module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function campbell_product_category_filtering_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the tnv_pathway module.
    case 'help.page.campbell_product_category_filtering':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom Blocks to integrate with Campbell\'s Product Category Pages.') . '</p>';
      return $output;

    default:
  }
}
