# SendGrid
sendgrid_key: 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
# Mailer
mailer_host:       smtp.sendgrid.net
mailer_port:       465
mailer_encryption: ssl
mailer_username:   wmdev
mailer_password:   mLbgBGgARPddh9WcProtFijB

