configuration_names:
  0: 'sata_core.settings:warranty_highest_exported_sid'
  2: 'webform.webform.*'
  4: 'sata.settings:logo_tagline.path'
  6: 'sata.settings:logo_tagline.use_default'
  8: 'sata.settings:logo_tagline.url'
  10: 'sata.settings:price_spider_hide'
  12: 'sata.settings:price_spider_generic_key'
  14: 'sata.settings:price_spider_product_key'
  16: 'sata.settings:price_spider_reviews_key'
  18: 'sata.settings:price_spider_account_key'
  20: 'sata.settings:price_spider_country'
  22: 'sata.settings:price_spider_language'
  24: 'sata.settings:cookiebot_cbid'
  26: 'sata.settings:favicon.use_default'
  28: 'sata.settings:favicon.path'
  30: 'sata.settings:favicon.mimetype'
  32: 'sata.settings:logo.use_default'
  34: 'sata.settings:logo.path'
  36: 'sata.settings:enable_w1_grid'
  38: 'sata.settings:price_spider_generic_product_button'
