_core:
  default_config_hash: l58O_yEXSo-SeJi19LXdzTU1tNJG3lmnIhCitRkM1tk
langcode: en
uuid: e572331e-4830-404b-b4cf-00dcc4c18610
name: 'SATA Ferramentas'
mail: no-reply@gearwrench.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/1
admin_compact_mode: false
weight_select_max: 100
default_langcode: pt-br
