_core:
  default_config_hash: leDs4zpOP2Rkz0I5UjDmwTPv85Xhta0rHSD4AjHE33o
country:
  default: BR
first_day: 0
timezone:
  default: America/Chicago
  user:
    configurable: true
    warn: false
    default: 0
