channels:
  -
    id: purgers
    grants:
      - 0
      - 2
      - 3
  -
    id: queue
    grants:
      - 0
      - 2
      - 3
  -
    id: diagnostics
    grants:
      - 3
  -
    id: purger_acquia_purge_4316d96217
    grants:
      - 0
      - 2
      - 3
  -
    id: purger_acquia_platform_cdn_7d2ad213d9
    grants:
      - 0
      - 2
      - 3
