sftp_host: azuseftp.blob.core.windows.net
sftp_username: azuseftp.stibovmlyr
sftp_password: Chh+mMov0pv7HQUHw1LC4R0dSrqaWD+9d46nx76t4mZhNB8qlemonfGNSwW9O/P9tO6+QIuJMmKIaRp3dP3CMA==
sftp_root_products_full: '/NA CT/Full'
sftp_root_products_delta: '/NA CT/Delta'
migration_name: crescenttool_products
last_downloaded_file_name: 'NA CT/Delta/Crescent_US_1665719430326.xml'
