warranty_sftp_host: ftpsapprod.apextoolgroup.com
warranty_sftp_username: ftpmagento
warranty_sftp_password: UbgrBlA3
warranty_sftp_root: /Magento/WarrantyExport/Queue
warranty_highest_exported_sid: 0
warranty_vendor_code: APEX-CRS-POR
warranty_sid_prepend: CRS
