_core:
  default_config_hash: xu0yG13sSQJcXrOJJqsn44W_hUWAIFHVlphrzxT2ycU
page_title: Sitemap
message:
  value: ''
  format: plain_text
plugins:
  frontpage:
    enabled: true
    weight: 0
    settings:
      title: 'Front page'
      rss: /rss.xml
    id: frontpage
    provider: sitemap
  'menu:featured-tools':
    enabled: true
    weight: 0
    settings:
      title: 'Featured Tools'
      show_disabled: false
    id: 'menu:featured-tools'
    provider: sitemap
  'menu:main':
    enabled: true
    weight: 0
    settings:
      title: 'Primary Links'
      show_disabled: false
    id: 'menu:main'
    provider: sitemap
  'menu:tools':
    enabled: true
    weight: 0
    settings:
      title: Tools
      show_disabled: false
    id: 'menu:tools'
    provider: sitemap
include_css: true
