transport: smtp
smtp_host: smtp.office365.com
smtp_port: 587
smtp_encryption: tls
smtp_credential_provider: swiftmailer
smtp_credentials:
  swiftmailer:
    username: no-reply@apextoolgroup.com
    password: 'd=Ad1+c3=c+G:*7sO8Y'''
sendmail_path: /usr/sbin/sendmail
sendmail_mode: bs
spool_directory: ''
_core:
  default_config_hash: RSNbRD3ekSaZoE19f3eHhm93gKOcD2PtmaAVmV3XMes
