_core:
  default_config_hash: m3ypoMoedILNeLX0GjGnjRTcVGXAqJnzib1_GNfHLz0
ignored_config_entities:
  - 'block.block.custom_*'
  - system.site
  - google_tag.container.google_tag_manager
  - google_tag.container.gtm_container
  - 'commerce_payment.commerce_payment_gateway.authorize_net_accept_js_*'
  - ecom_azure_api.settings
  - commerce_custom_stock.settings
