ecom_app_token_url: 'https://login.microsoftonline.com/231bbb7c-1b4b-43dc-bcb5-c40e5f722be5/oauth2/v2.0/token'
ecom_app_auth_scope: 'https://graph.microsoft.com/.default'
ecom_app_auth_grant: client_credentials
ecom_client_token_url: 'https://login.microsoftonline.com/231bbb7c-1b4b-43dc-bcb5-c40e5f722be5/oauth2/v2.0/token'
ecom_client_auth_scope: 'openid profile email'
ecom_client_auth_grant: password
ecom_tenant: 231bbb7c-1b4b-43dc-bcb5-c40e5f722be5
ecom_client_id: 1b2cf885-bdc6-4b13-af26-73c624920d0a
ecom_client_secret: 5468Q~z8O9TqbJZtrulrC-m6cl1-p6bUOq7cEcBe
ecom_address_list:
  - 172.19.0.1
ecom_graph_user_api: 'https://graph.microsoft.com/beta/users'
ecom_app_cache_expire: '3599'
