ecom_app_token_url: 'https://login.microsoftonline.com/oauth2/v2.0/token'
ecom_app_auth_scope: 'https://graph.microsoft.com/.default'
ecom_app_auth_grant: client_credentials
ecom_client_token_url: 'https://login.microsoftonline.com/oauth2/v2.0/token'
ecom_client_auth_scope: 'openid profile email'
ecom_client_auth_grant: password
ecom_tenant: ''
ecom_client_id: ''
ecom_client_secret: ''
ecom_address_list: ''
ecom_graph_user_api: 'https://graph.microsoft.com/beta/users'
ecom_app_cache_expire: '3599'
