<?php

use Drupal\Core\Entity\EntityInterface;
use \Drupal\Core\Cache\RefinableCacheableDependencyInterface;
/**
 * Implements hook_node_presave().
 *
 * Setting 2nd and 3rd level category facets for child product categories.
 */
function ecom_common_node_presave(EntityInterface $entity) {
  if ($entity->bundle() !== 'product_category') {
    return;
  }

  $classification_id = $entity->get('field_classification_id')->getValue()[0]['value'];
  $classification_array = explode('_', $classification_id);

  if ($classification_array[0] !== 'W3' && $classification_array[0] !== 'W4') {
    return;
  }

  $term_ids = $entity->get('field_product_classifications')->getValue();
  if (empty($term_ids)) {
    return;
  }

  // Get the first term ID from the array of entity references.
  $first_term_id = reset($term_ids);
  $child_term_id = $first_term_id['target_id'] ?? NULL;

  $child_term = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadAllParents($child_term_id);
  $child_term = array_values($child_term);
  $count = count($child_term);
  $second_level_parent = $child_term[$count-2];

  $term_classification_id = $second_level_parent->get('field_classification_id')->getValue()[0]['value'];

  $parent_nid = \Drupal::entityQuery('node')
    ->condition('field_classification_id', $term_classification_id)
    ->accessCheck(FALSE)
    ->range(0, 1)
    ->execute();
  if (!$parent_nid) {
    return;
  }

  $parent_node = \Drupal::entityTypeManager()->getStorage('node')->load(reset($parent_nid));
  $field_category_facets_value = $parent_node->get('field_category_facets')->getValue();
  $entity->set('field_category_facets', $field_category_facets_value);
}

/**
 * Implements hook_entity_type_alter().
 */
function ecom_common_entity_type_alter(array &$entity_types) {
  $entity_types['commerce_wishlist']->setHandlerClass('form', array(
    'default' => 'Drupal\commerce_wishlist\Form\WishlistForm',
    'user' => 'Drupal\ecom_common\Form\EcomWishlistUserForm',
    'share' => 'Drupal\commerce_wishlist\Form\WishlistShareForm',
    'duplicate' => 'Drupal\commerce_wishlist\Form\WishlistForm',
    'delete' => 'Drupal\Core\Entity\ContentEntityDeleteForm'
  ));
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function ecom_common_menu_local_tasks_alter(&$data, $route_name, RefinableCacheableDependencyInterface &$cacheability) {

  $route_array = [
    'view.commerce_user_orders.order_page',
    'entity.user.edit_form',
    'commerce_order.address_book.overview',
    'commerce_wishlist.user_page',
    'entity.user.canonical',
    'ecom_common.account_dashboard',
    'entity.commerce_order.user_view',
    'commerce_order.address_book.edit_form',
  ];
  if (in_array($route_name, $route_array)) {
    // My Order Tab.
    $data['tabs'][0]['views_view:view.commerce_user_orders.order_page']['#link']['title'] = t('My Orders');
    $data['tabs'][0]['views_view:view.commerce_user_orders.order_page']['#weight'] = -48;

    if ($route_name == 'entity.commerce_order.user_view') {
      $data['tabs'][0]['entity.commerce_order.user_view']['#access'] = FALSE;
      $data['tabs'][0]['views_view:view.commerce_user_orders.order_page']['#weight'] = -48;
    }
    if ($route_name == 'commerce_order.address_book.edit_form') {
      $data['tabs'][0]['commerce_order.address_book.overview']['#access'] = FALSE;
      $data['tabs'][0]['commerce_order.address_book.edit_form']['#weight'] = -49;
    }
    // Shortcut Tab.
    $data['tabs'][0]['shortcut.set_switch']['#access'] = FALSE;
    // Submission Tab.
    $data['tabs'][0]['entity.webform_submission.user']['#access'] = FALSE;
    // Payment Method Tab.
    $data['tabs'][0]['entity.commerce_payment_method.collection']['#access'] = FALSE;
    // My Wishlist Tab.
    $data['tabs'][0]['entity.commerce_wishlist.user_page']['#link']['title'] = t('My Wishlist');
    $data['tabs'][0]['entity.commerce_wishlist.user_page']['#weight'] = -47;
    // User Edit Tab.
    $data['tabs'][0]['entity.user.edit_form']['#link']['title'] = t('Account Information');
    $data['tabs'][0]['entity.user.edit_form']['#weight'] = -50;
    // Address book Tab.
    $data['tabs'][0]['commerce_order.address_book.overview']['#weight'] = -49;
    // View Tab.
    $data['tabs'][0]['entity.user.canonical']['#access'] = FALSE;
  }
}


