<?php

use Drupal\Core\Entity\EntityInterface;
/**
 * Implements hook_node_presave().
 *
 * Setting 2nd and 3rd level category facets for child product categories.
 */
function ecom_common_node_presave(EntityInterface $entity) {
  if ($entity->bundle() !== 'product_category') {
    return;
  }

  $classification_id = $entity->get('field_classification_id')->getValue()[0]['value'];
  $classification_array = explode('_', $classification_id);

  if ($classification_array[0] !== 'W3' && $classification_array[0] !== 'W4') {
    return;
  }

  $term_ids = $entity->get('field_product_classifications')->getValue();
  if (empty($term_ids)) {
    return;
  }

  // Get the first term ID from the array of entity references.
  $first_term_id = reset($term_ids);
  $child_term_id = $first_term_id['target_id'] ?? NULL;

  $child_term = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadAllParents($child_term_id);
  $child_term = array_values($child_term);
  $count = count($child_term);
  $second_level_parent = $child_term[$count-2];

  $term_classification_id = $second_level_parent->get('field_classification_id')->getValue()[0]['value'];

  $parent_nid = \Drupal::entityQuery('node')
    ->condition('field_classification_id', $term_classification_id)
    ->accessCheck(FALSE)
    ->range(0, 1)
    ->execute();
  if (!$parent_nid) {
    return;
  }

  $parent_node = \Drupal::entityTypeManager()->getStorage('node')->load(reset($parent_nid));
  $field_category_facets_value = $parent_node->get('field_category_facets')->getValue();
  $entity->set('field_category_facets', $field_category_facets_value);
}
