sftp_host: azuseftp.blob.core.windows.net
sftp_username: azuseftp.stibovmlyr
sftp_password: Chh+mMov0pv7HQUHw1LC4R0dSrqaWD+9d46nx76t4mZhNB8qlemonfGNSwW9O/P9tO6+QIuJMmKIaRp3dP3CMA==
sftp_root_products_full: '/SATA CO/Full'
sftp_root_products_delta: '/SATA CO/Delta'
migration_name: sata_colombia_products
last_downloaded_file_name: ''
site_sales_org: 8301
