configuration_names:
  0: 'sata_core.settings:warranty_highest_exported_sid'
  2: 'webform.webform.*'
  4: 'sata.settings:logo_tagline.path'
  6: 'sata.settings:logo_tagline.use_default'
  8: 'sata.settings:logo_tagline.url'
  10: 'sata.settings:price_spider_hide'
  12: 'sata.settings:price_spider_generic_key'
  14: 'sata.settings:price_spider_product_key'
  16: 'sata.settings:price_spider_country'
  18: 'sata.settings:price_spider_language'
  20: 'sata.settings:cookiebot_cbid'
