features:
  node_user_picture: 1
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 0
  path: 'public://tagline-co_0.svg'
  mimetype: image/svg+xml
logo_tagline:
  path: 'public://tagline-co_0.svg'
  use_default: 0
  url: '/sites/sata_colombia/files/tagline-co_0.svg'
enable_w1_grid: 0
price_spider_hide: 0
price_spider_generic_key: ''
price_spider_product_key: ''
price_spider_country: ''
price_spider_language: ''
cookiebot_cbid: ''
