_core:
  default_config_hash: l58O_yEXSo-SeJi19LXdzTU1tNJG3lmnIhCitRkM1tk
langcode: en
uuid: 2388dc4b-a4d6-4c1b-9a38-ba0e4f807ba7
name: 'SATA Colombia'
mail: no-reply@gearwrench.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/6
admin_compact_mode: false
weight_select_max: 100
default_langcode: es
