_core:
  default_config_hash: xu0yG13sSQJcXrOJJqsn44W_hUWAIFHVlphrzxT2ycU
page_title: 'Site Map'
message:
  value: ''
  format: plain_text
plugins:
  frontpage:
    enabled: false
  'menu:main':
    enabled: true
    weight: 0
    settings:
      title: ''
      show_disabled: false
    id: 'menu:main'
    provider: sitemap
include_css: true
