_core:
  default_config_hash: leDs4zpOP2Rkz0I5UjDmwTPv85Xhta0rHSD4AjHE33o
first_day: 0
country:
  default: US
timezone:
  default: America/Chicago
  user:
    configurable: true
    default: 0
    warn: false
