features:
  node_user_picture: 1
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 1
  path: ''
favicon:
  use_default: 0
  path: themes/custom/sata/favicons/favicon.ico
  mimetype: image/vnd.microsoft.icon
price_spider_generic_key: ''
price_spider_hide: 1
price_spider_country: ''
price_spider_language: ''
price_spider_product_key: ''
