features:
  node_user_picture: 1
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 1
  path: ''
favicon:
  use_default: 0
  path: themes/custom/sata/favicons/favicon.ico
  mimetype: image/vnd.microsoft.icon
price_spider_generic_key: 2377-63050151745ebe000edcd360
price_spider_hide: 0
price_spider_country: US
price_spider_language: en
price_spider_product_key: 2377-63050130cb2c6c000dda36f9
logo_tagline:
  path: 'public://tagline-us.svg'
  use_default: 0
  url: /sites/sata_us/files/tagline-us.svg
enable_w1_grid: 0
cookiebot_cbid: ''
