_core:
  default_config_hash: l58O_yEXSo-SeJi19LXdzTU1tNJG3lmnIhCitRkM1tk
langcode: en
uuid: de0fd387-4462-441d-9bc4-cce47b4a9e16
name: SATA
mail: no-reply@satatools.us
slogan: ''
page:
  403: /node/3641
  404: ''
  front: /node/31
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
