<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\node\Entity\Node;

/**
 * Implements hook_theme
 */
function helpers_theme($existing, $type, $theme, $path) {
  return [
    'views_view_tabs_list' => [
      'variables' => [
        'view' => null,
        'rows' => null,
      ],
      $path = \Drupal::service('extension.list.module')->getPath('helpers') . '/templates',
    ],
    'views_view_tab' => [
      'variables' => [
        'entity' => null,
        'current' => null,
      ],
    ],
  ];
}

/**
 * Prepares variables for views demo_bootstrap_tabs template.
 *
 * Template: demo-bootstrap-tabs.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - view: The view object.
 *   - rows: An array of row items. Each row is an array of content.
 */
function template_preprocess_views_view_tabs_list(&$variables) {
  /** @var \Drupal\views\ViewExecutable $view */
  $view = $variables['view'];
  $rows = $variables['rows'];
  $variables['tabs'] = [];
  $variables['current'] = $view->getRequest()->get('taxonomy_term');

  $nav = [];
  foreach ($rows as $id => $row) {
    $entity = $row['#row']->_entity;
    $nav[$id] = [
      '#theme' => 'views_view_tab',
      '#view' => $view,
      '#row' => $row['#row'],
      '#entity' => $entity,
      '#current' => $variables['current']
    ];
  }

  template_preprocess_views_view_unformatted($variables);

  $variables['tabs'] = $nav;
}


/**
 * Implements hook_form_alter().
 */
function helpers_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  if($form_id == 'node_hubspot_form_edit_form') {
    $form['field_form_link']['#states'] = [
    'visible' => [
      ':input[name="field_not_a_hubspot_form[value]"]' => ['checked' => TRUE],
      ],
    ];

    $form['field_hubspot_code']['#states'] = [
    'visible' => [
      ':input[name="field_hubspot_form[value]"]' => ['checked' => TRUE],
      ],
    ];
  }
}
