<?php

/**
 * @file
 * Primary module hooks for ecom_azure_api module.
 */

use Drupal\Core\Routing\TrustedRedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\Core\Cache\Cache;
use Drupal\Core\Render\Markup;

/**
 * Implements hook_form_alter().
 */
function ecom_azure_api_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == "ecom_azure_config_form") {
    $form['#submit'][] = 'ecom_azure_api_azure_config_form_submit';
  }
}

/**
 * Implements hook_theme().
 */
function ecom_azure_api_theme($existing, $type, $theme, $path) {
  return [
    'page__ad_login' => [
      'variables' => [
        'form' => ''
      ]
    ],
  ];
}

/**
 * Clear Azure settings cache.
 */
function ecom_azure_api_azure_config_form_submit(array &$form, FormStateInterface $form_state) {
  drupal_flush_all_caches();
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function ecom_azure_api_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  if (\Drupal::routeMatch()->getRouteName() == "ecom_azure_api.network_login") {
    $suggestions[] = 'page__ad_login';
  }
}
