<?php

/**
 * @file
 * Hook implementations of ecom_addrexx module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter() for address field forms.
 */
function ecom_addrexx_form_alter(array &$form, FormStateInterface &$form_state, $form_id) {
  $target_form_ids = [
    'profile_customer_edit_form',
    'profile_customer_add_form',
    'profile_customer_address-book-edit_form',
    'profile_customer_address-book-add_form',
  ];

  if (in_array($form_id, $target_form_ids) || ($form_id == 'commerce_checkout_flow_multistep_default' && $form['#step_id'] == 'order_information')) {
    $form['#attached']['library'][] = 'ecom_addrexx/autocomplete_ajax';

    if (in_array($form_id, $target_form_ids)) {
      $title = ($form_id == 'profile_customer_add_form' || $form_id == 'profile_customer_address-book-add_form') ? t('Add New Address') : t('Edit Address');

      $form['address_title'] = [
        '#type' => 'item',
        '#markup' => "<b>$title</b>",
        '#weight' => -100,
      ];
    }
  }
}
