channels:
  -
    id: purgers
    grants:
      - 0
      - 2
      - 3
  -
    id: queue
    grants:
      - 0
      - 2
      - 3
  -
    id: purger_acquia_purge_1aa2682023
    grants:
      - 0
      - 2
      - 3
  -
    id: diagnostics
    grants:
      - 3
  -
    id: purger_acquia_platform_cdn_71bb6a2cd9
    grants:
      - 0
      - 2
      - 3
