<?php

/**
 * @file
 * Contains atg_mailing_list.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function atg_mailing_list_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
      // Main module help for the atg_mailing_list module.
    case 'help.page.atg_mailing_list':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Places a newsletter signup widget in the footer of every page.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_preprocess_html()
 */
function atg_mailing_list_preprocess_html(&$variables)
{
  if (\Drupal::service('router.admin_context')->isAdminRoute()) return;

  $settings = \Drupal::config('atg_mailing_list.settings');
  $mailing_list = [
    'title' => null,
    'form' => null,
    'display' => false,
  ];

  if ($settings->get('atg_mailing_list_enable') === 1) {
    $mailing_list['title'] = $settings->get('atg_mailing_list_title');
    $mailing_list['form'] = $settings->get('atg_mailing_list_form');
  }

  $node = \Drupal::request()->attributes->get('node');
  if ($node) {
    if ($node->hasField('field_mailing_list_form')) {
      $field_mailing_list_form = $node->get('field_mailing_list_form')->getValue();
      if (count($field_mailing_list_form) && $field_mailing_list_form[0]['target_id']) {
        $paragraph = \Drupal\paragraphs\Entity\Paragraph::load($field_mailing_list_form[0]['target_id']);
        $mailing_list['display'] = (bool) $paragraph->field_mailing_list_form_display->getValue()[0]['value'];
      }
    }
  }

  $variables['mailing_list'] = $mailing_list;
}
