cancel_confirm:
  subject: 'Solicitud de cancelación de cuenta para [user:display-name] en [site:name]'
password_reset:
  subject: 'Reemplazo de información de inicio de sesión para [user:display-name] en [site:name]'
register_admin_created:
  subject: 'Un administrador ha creado una cuenta para usted en [site:name]'
register_no_approval_required:
  subject: 'Detalles de la cuenta para [user:display-name] en [site:name]'
register_pending_approval:
  subject: 'Detalles de cuenta para [user:display-name] en [site:name] (pendiente de aprobación por el administrador)'
register_pending_approval_admin:
  subject: 'Detalles de cuenta para [user:display-name] en [site:name] (pendiente de aprobación por el administrador)'
status_activated:
  subject: 'Detalles de cuenta para [user:display-name] en [site:name] (aprobado)'
status_blocked:
  subject: 'Detalles de la cuenta de [user:display-name] en [site:name] (bloqueada)'
status_canceled:
  subject: 'Detalles de cuenta para [user:display-name] en [site:name] (cancelado)'
