sftp_host: azuseftp.blob.core.windows.net
sftp_username: azuseftp.stibovmlyr
sftp_password: Chh+mMov0pv7HQUHw1LC4R0dSrqaWD+9d46nx76t4mZhNB8qlemonfGNSwW9O/P9tO6+QIuJMmKIaRp3dP3CMA==
sftp_root_products_full: '/NA GW/Full'
sftp_root_products_delta: '/NA GW/Delta'
migration_name: gearwrench_products
last_downloaded_file_name: 'NA GW/Delta/GEARWRENCH_US_1665719427409.xml'
site_sales_org: 1201
