sftp_host: azuseftp.blob.core.windows.net
sftp_username: azuseftp.stibovmlyr
sftp_password: Chh+mMov0pv7HQUHw1LC4R0dSrqaWD+9d46nx76t4mZhNB8qlemonfGNSwW9O/P9tO6+QIuJMmKIaRp3dP3CMA==
sftp_root_products_full: /NA%20GW/Full
sftp_root_products_delta: /NA%20GW/Delta
