_core:
  default_config_hash: m3ypoMoedILNeLX0GjGnjRTcVGXAqJnzib1_GNfHLz0
ignored_config_entities:
  - 'block.block.custom_*'
  - 'gearwrench_core.settings:warranty_highest_exported_sid'
  - 'acquia_connector.settings:spi.site_environment'
  - 'acquia_connector.settings:spi.site_uuid'
  - 'search_api.server.acquia_search_server:backend_config.connector_config'
  - 'webform.webform.*'
  - ~webform.webform.warranty_abusers
  - ~webform.webform.warranty_replacement_form
  - 'gearwrench.settings:cookiebot_cbid'
