features:
  node_user_picture: 1
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 0
  path: themes/custom/gearwrench/favicons/favicon.ico
  mimetype: image/vnd.microsoft.icon
cookiebot_cbid: '707cee35-0174-4156-959c-f868344ef453'
