<?php

/**
 * @file
 * Provides a quotation entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function apex_tools_custom_quotation_theme() {
  return [
    'quotation' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for quotation templates.
 *
 * Default template: quotation.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the quotation information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_quotation(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
