version: "2.1"

services:
  mail:
    hostname: mail
    image: mailhog/mailhog
    expose:
      - "80"
    environment:
      - MH_API_BIND_ADDR=0.0.0.0:80
      - MH_UI_BIND_ADDR=0.0.0.0:80
    labels:
      - io.docksal.virtual-host=webmail.${VIRTUAL_HOST}
    user: root
  web:
    labels:
      - io.docksal.virtual-host=apex-tools.docksal,*.apex-tools.docksal,crescenttool.docksal,*.crescenttool.docksal,gearwrench.docksal,*.gearwrench.docksal,crescenttool.com.au.docksal,*.crescenttool.com.au.docksal,gearwrench.com.au.docksal,*.gearwrench.com.au.docksal,*.sataferramentas.com.br.docksal,*.sata.com.co.docksal,*.satatools.eu.docksal,*.satatools.us.docksal
  solr:
    image: docksal/solr:8.1
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: solr
  cli:
    environment:
      - XDEBUG_CONFIG=client_host=${DOCKSAL_HOST_IP} client_port=9000
      - XDEBUG_MODE=debug
      - PHP_IDE_CONFIG=serverName=${VIRTUAL_HOST}
      - DRUSH_ALLOW_XDEBUG=${XDEBUG_ENABLED:-0}
      - DRUSH_OPTIONS_URI=${VIRTUAL_HOST}
