<?php

use Drupal\Core\Form\FormStateInterface;

function atg_cleverreach_form_alter(&$form, FormStateInterface $form_state, $form_id)
{
    // Checks if we should submit to CleverReach based on our hidden field value and language code
    if (isset($form['elements']['cleverreach_id']) && !empty($form['elements']['cleverreach_id']['#default_value'])) {
        $language = Drupal::languageManager()->getCurrentLanguage()->getId();
        if ($language != 'en' && $form['elements']['cleverreach_id']['#default_value'] != 'null') {
            $form['actions']['submit']['#submit'][] = 'atg_cleverreach_generate_lead';
        }
    }

    /**
     * Set form From Website field value to current URL
     */
    if (array_key_exists('elements', $form) && is_array($form['elements'])) {
      foreach (['from_website', 'from_website____'] as $field) {
        if (array_key_exists($field, $form['elements'])) {
          $from_website = 'http'
            . (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? 's' : '')
            . '://' . $_SERVER['HTTP_HOST']
            . $_SERVER['REQUEST_URI'];

          // Append the requested resource location to the URL
          $form['elements'][$field]['#default_value'] = $from_website;
        }
      }
    }
}

function atg_cleverreach_generate_lead(&$form, FormStateInterface &$form_state)
{
    Drupal::service('atg_cleverreach.cleverreach_service')->generateLead($form_state);
}
