<?php

/**
 * @file
 * Primary module hooks for price spider where to buy module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Config;

/**
 * Implements hook_theme().
 */
function price_spider_where_to_buy_theme() {
  $theme['price_spider_where_to_buy'] = [
    'render element' => 'elements',
    'template' => 'block--price-spider-where-to-buy',
    'variables' => [
      'price_spider_generic_key' => NULL,
    ],
  ];

  return $theme;
}
