_core:
  default_config_hash: ttd8HXcqwSjGgp-fWA3gUA8q4TNvXB0a72pkFlnF56g
hotlink: false
origin: 'https://stg-www.apextoolgroup.com'
origin_dir: sites/apextoolgroup/files
use_imagecache_root: true
verify: true
excluded_extensions: ''
