<?php

/**
 * @file
 * Primary module hooks for Apex Tools Instagram Feed module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\TrustedRedirectResponse;
use Drupal\Core\Url;
use GuzzleHttp\Exception\RequestException;
use Facebook\Facebook;

/**
 * Implements hook_form_alter().
 */
function apex_tools_instagram_feed_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id === 'apex_tools_instagram_feed_settings') {
    $form['#submit'][] = 'apex_tools_instagram_feed_auth_callback';
  }
}

/**
 * Custom Form Callback to redirect to Facebook App Auth Screen.
 */
function apex_tools_instagram_feed_auth_callback($form, FormStateInterface $form_state) {
  $app_id = $form_state->getValue('app_id');
  $app_secret = $form_state->getValue('app_secret');
  $redirect_uri = $form_state->getValue('redirect_uri');
  $facebook_creds = [
    'app_id' => $app_id,
    'app_secret' => $app_secret,
    'default_graph_version' => 'v12.0',
    'persistent_data_handler' => 'session'
  ];
  $facebook = new Facebook($facebook_creds);
  $helper = $facebook->getRedirectLoginHelper();
  $permissions = [
    'public_profile',
    'instagram_basic',
    'pages_show_list'
  ];
  $login_url = $helper->getLoginUrl($redirect_uri, $permissions);
  $response = new TrustedRedirectResponse(Url::fromUri($login_url)->toString());
  $form_state->setResponse($response);
}

/**
 * Implements hook_cron().
 */
function apex_tools_instagram_feed_cron() {
  $service_provider = \Drupal::service('apex_tools_instagram_feed.service_provider');
  $access_token = \Drupal::state()->get('access_token');
  if (!empty($access_token)) {
    $facebook_page_id = $service_provider->getFaceBookPageId();
    if (!empty($facebook_page_id)) {
      $instagram_account_id = $service_provider->getInstagramAccountId($facebook_page_id);
      if (!empty($instagram_account_id)) {
        $service_provider->getInstagramMediaItems();
      }
    }
  }
}
