cancel_confirm:
  subject: 'Solicitação de cancelamento de conta para [user:display-name] em [site:name]'
password_reset:
  subject: 'Novas informações de autenticação para [user:display-name] em [site:name]'
register_admin_created:
  subject: 'Um administrador criou uma conta para você no site [site:name]'
register_no_approval_required:
  subject: 'Detalhes de conta para [user:display-name] em [site:name]'
register_pending_approval:
  subject: 'Detalhes de conta para [user:display-name] em [site:name] (aguardando aprovação de um administrador)'
register_pending_approval_admin:
  subject: 'Detalhes de conta para [user:display-name] em [site:name] (aguardando aprovação de um administrador)'
status_activated:
  subject: 'Detalhes da conta para [user:display-name] em [site:name] (aprovada)'
status_blocked:
  subject: 'Detalhes da conta para [user:display-name] em [site:name] (bloqueada)'
status_canceled:
  subject: 'Detalhes da conta para [user:display-name] em [site:name] (cancelada)'
