display:
  default:
    display_title: Standard
    display_options:
      title: Medien
      fields:
        media_bulk_form:
          action_title: Action
      pager:
        options:
          tags:
            next: ››
            previous: ‹‹
          expose:
            items_per_page_label: 'Elemente pro Seite'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Versatz
      exposed_form:
        options:
          reset_button_label: Zurücksetzen
          exposed_sorts_label: 'Sortieren nach'
          sort_asc_label: Aufsteigend
          sort_desc_label: Absteigend
      empty:
        area_text_custom:
          content: 'No content available.'
      sorts:
        created:
          expose:
            label: 'Neuestes zuerst'
      filters:
        status:
          expose:
            label: Veröffentlichungsstatus
          group_info:
            label: Veröffentlicht
            group_items:
              1:
                title: Veröffentlicht
              2:
                title: 'Nicht veröffentlicht'
        name:
          expose:
            label: Name
        bundle:
          expose:
            label: Medientyp
          group_info:
            label: Medientyp
        langcode:
          expose:
            label: Language
  page:
    display_title: Seite
    display_options:
      fields:
        media_bulk_form:
          action_title: Action
        name:
          separator: ', '
        edit_media:
          text: Edit
        delete_media:
          text: Delete
  widget:
    display_title: Steuerelement
    display_options:
      arguments:
        bundle:
          exception:
            title: Alle
      filters:
        name:
          expose:
            label: Name
      header:
        display_link_grid:
          label: Raster
        display_link_table:
          label: Tabelle
  widget_table:
    display_options:
      fields:
        thumbnail__target_id:
          label: Miniaturbild
        name:
          label: Name
        uid:
          label: Autor
        changed:
          label: Aktualisiert
      arguments:
        bundle:
          exception:
            title: Alle
      filters:
        name:
          expose:
            label: Name
      header:
        display_link_grid:
          label: Raster
        display_link_table:
          label: Tabelle
