apex_common.settings:
  type: config_object
  label: 'Apex Common Configuration'
  mapping:
    warranty_sftp_host:
      type: text
      label: 'Warranty Upload sFTP Host'
    warranty_sftp_username:
      type: text
      label: 'Warranty Upload sFTP Username'
    warranty_sftp_password:
      type: text
      label: 'Warranty Upload sFTP Password'
    warranty_sftp_root:
      type: text
      label: 'Warranty Upload sFTP Root path to upload to'
    warranty_vendor_code:
      type: text
      label: 'Warranty Upload sFTP Root path to upload to'
