<?php

/**
 * @file
 * Primary module hooks for Gearwrench Migrations module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\migrate\Plugin\MigrateSourceInterface;
use Drupal\migrate\Plugin\MigrationInterface;
use Drupal\migrate\Row;

/**
 * Implements hook_migrate_prepare_row().
 */
function gearwrench_migrations_migrate_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration)
{
//  dump($row);
}

//function gearwrench_migrations_preprocess_html(&$variables) {
//  $name = 'Auto Specialty';
//  if (!empty($name)) {
//    $properties['name'] = $name;
//  }
//  if (!empty($vocabulary)) {
//    $properties['vid'] = 'product_classifications';
//  }
//  $terms = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadByProperties($properties);
//  foreach ($terms as $term) {
//    dump($term);
//    if ($term->hasField('field_classification_id')) {
//      $id_to_check = $term->get('field_classification_id')->value;
//      dump($id_to_check);
//    }
//
//  }
//
//}
