_core:
  default_config_hash: 3YOzr3tRCT69NVNsWlRBu6-DWMfgetumWFM9Jqp6vqc
favicon:
  use_default: 0
  path: ''
logo:
  use_default: 1
  path: ''
features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 0
