atg_callout_enable: 1
atg_callout_position: right
atg_callout_title: 'Download Our Catalog'
atg_callout_copy: 'Click here to view our full product catalog.'
atg_callout_path: 'https://www.paperturn-view.com/us/cptmarketing/cleco-2019-digital-catalog?pid=NTg58319&v=2.1'
atg_callout_path_de: 'https://www.paperturn-view.com/de/cptmarketing/cleco-produktkatalog-sp-1081-de-12112020?pid=MTI124292&v=1.1'
atg_callout_target: 1
atg_callout_image_path: ''
atg_callout_image_upload:
  - '557'
atg_callout_image_upload_de:
  - '549'
