_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
ignored_config_entities:
  - system.site
  - language.negotiation
  - apex_migrations.settings
  - atg_callout.settings
  - apex_tools_custom_quotation.csqw_settings
  - block.block.customlanguageswitcher
