_core:
  default_config_hash: yFE1nEOaD0XSv9vzdabMHPyYvo9An7fYVq_yAQgJK_I
langcode: en
cookiebot_cbid: 9ba9aabd-ed90-45e0-9aae-5f1178577820
cookiebot_block_cookies: true
cookiebot_iab_enabled: false
cookiebot_show_declaration: false
cookiebot_show_declaration_node: null
exclude_paths: ''
exclude_admin_theme: false
exclude_uid_1: false
message_placeholder_cookieconsent_optout_marketing_show: false
message_placeholder_cookieconsent_optout_marketing:
  value: "<p>Please <a class=\"cookieconsent-optout-marketing__cookiebot-renew\" href=\"!cookiebot_renew\">accept marketing-cookies</a> to view this embedded content from <a class=\"cookieconsent-optout-marketing__from-src-url\" href=\"!cookiebot_from_src_url\" target=\"_blank\">!cookiebot_from_src_url</a></p>\r\n"
  format: full_html
cookiebot_show_declaration_node_path: /node/
cookiebot_drupal_culture: 0
