<?php

/**
 * @file
 * Primary module hooks for Campbell Common module.
 */

/**
 * Implements hook_theme().
 */
function campbell_common_theme($existing, $type, $theme, $path) {
    return [
      'taxonomy_terms_view' => [
        'variables' => [
          'welded_chain' => NULL,
          'forged_fittings' => NULL,
          'cable_and_wire_rope' => NULL,
          'weldless_chain' => NULL,
          'hobby_craft_and_deco' => NULL,
          'assemblies' => NULL,
          'overhead_lifting' => NULL,
          'lifting_clamps' => NULL,
          'blocks' => NULL,
          'accessories' => NULL,
          'pre_cut_packaged' => NULL,
          'chain_and_cable_cutters' => NULL,
          'featuredblock' => NULL,
        ],
      ],
    ];
  }


/**
 * Implements hook_preprocess_breadcrumb().
 *
 * Adding long description as last element in Breadcrumb for products.
 */
function campbell_common_preprocess_breadcrumb(&$variables) {

  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node instanceof \Drupal\node\NodeInterface) {
    // Check if the content type is "product".
    if ($node->getType() == 'product') {

      //Getting long description field value for products
      $long_description_value = $node->get('field_long_description')->value;

      //Getting the last key of breadcrumb
      $last_key = array_key_last($variables['breadcrumb']);

      //Setting the text value of last key of product's breadcrumb
      $variables['breadcrumb'][$last_key]['text'] = $long_description_value;
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function campbell_common_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

  if (strpos($form_id, 'webform_submission_contact_us_') === 0) {
    $form['#prefix'] = '<div class="contact-title">Email us:</div>';
    $form['actions']['reset'] = [
      '#type' => 'button',
      '#value' => t('Clear Form'),
      '#weight' => 51,
      '#attributes' => array('onclick' => 'this.form.reset(); return false;'),
      '#suffix' => '<div class="required-fields-contact"><span class="color-red">*</span>Required field.</div>',

    ];
  }
}

