#!/usr/bin/env bash

#: exec_target = cli

## Initializes and installs project services (like npm, phpcs, etc.).
##
## Usage: fin init-services

#-------------------------- BEGIN: Helper functions --------------------------------
SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT=${PROJECT_ROOT:-"${SCRIPT_PATH}/../../"}
source "${PROJECT_ROOT}/.docksal/functions.sh"

#-------------------------- CLOSE: Helper functions --------------------------------

#-------------------------- BEGIN: Execution --------------------------------

header "Fixes for global composer"
section=Composer
step=1

step_header "Updating Drupal coder and PHP Codesniffer"
composer global require drupal/coder:8.3.13 squizlabs/php_codesniffer:^3.7.1
composer global update --with-dependencies drupal/coder

step_header "Removing a package that is incompoatible with PHP 8.1"
composer global remove consolidation/cgr

#-------------------------- CLOSE: Execution --------------------------------
