_core:
  default_config_hash: ndtrVaBQ-HbpHV7GJt-yNv3ITF7i8HSlR6mMQJeJOmo
sftp_host: azuseftp.blob.core.windows.net
sftp_username: azuseftp.stibovmlyr
sftp_password: Chh+mMov0pv7HQUHw1LC4R0dSrqaWD+9d46nx76t4mZhNB8qlemonfGNSwW9O/P9tO6+QIuJMmKIaRp3dP3CMA==
sftp_root_products_full: '/NA CL/Full'
sftp_root_products_delta: '/NA CL/Delta'
sftp_directory: '/NA CL/Full'

sftp_directory_de: '/EMEA CL/Full'
sftp_root_products_full_de: '/EMEA CL/Full'
sftp_root_products_delta_de: '/EMEA CL/Delta'
