cleverreach_api_key: ''
cleverreach_client_id: aefyFRg30c
cleverreach_client_login: ''
cleverreach_client_pswd: ''
cleverreach_api_endpoint: 'https://rest.cleverreach.com/v3'
cleverreach_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJyZXN0LmNsZXZlcnJlYWNoLmNvbSIsImlhdCI6MTUzNzIwMjE3NCwiZXhwIjoxNTM3MjAyNzc0LCJjbGllbnRfaWQiOjgzNzIsInNoYXJkIjoic2hhcmQ0Iiwiem9uZSI6MSwidXNlcl9pZCI6MCwibG9naW4iOiJhZWZ5RlJnMzBjIiwicm9sZSI6InVzZXIiLCJzY29wZXMiOiJvYV9iYXNpYyBvYV9yZWNlaXZlcnMgb2FfZm9ybXMgb2FfbWFpbGluZ3MiLCJpbmRlbnRpZmllciI6InN5c3RlbSIsImNhbGxlciI6MX0.jwLXrwaLg3x9Yfzw9Eb4PTimv0IepyzJE4V4ylJW5uE
cleverreach_client_secret: Pk1N05QOGNtTA5IkkzXLm70CGFuXJv9y
