_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
ignored_config_entities:
  - system.site
  - language.negotiation
  - google_tag.container.gtm_container
  - imperva_cache_purger.settings
