_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  address: 0
  acquia_search: 0
  admin_toolbar: 0
  advagg: 0
  advagg_js_minify: 0
  apex_migrations: 0
  advagg_css_minify: 0
  atg_api: 0
  atg_callout: 0
  atg_ckeditor: 0
  atg_cleverreach: 0
  atg_clone: 0
  atg_custom_tokens: 0
  atg_mail: 0
  atg_mailing_list: 0
  atg_menu_link_field: 0
  atg_translation: 0
  automated_cron: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  captcha: 0
  ckeditor: 0
  cleco_migrations: 0
  cleco_vuejs: 0
  color: 0
  comment: 0
  config: 0
  config_export_ignore: 0
  config_filter: 0
  config_ignore: 0
  config_split: 0
  config_translation: 0
  contact: 0
  contact_storage: 0
  content_moderation: 0
  content_sync: 0
  contextual: 0
  cookiebot: 0
  ctools: 0
  ctools_block: 0
  datetime: 0
  drupalmoduleupgrader: 0
  dynamic_entity_reference: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  edit_uuid: 0
  editor: 0
  entity: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_reference_revisions: 0
  entity_usage: 0
  feeds: 0
  feeds_tamper: 0
  field: 0
  field_ui: 0
  file: 0
  file_mdm: 0
  file_mdm_exif: 0
  file_mdm_font: 0
  filter: 0
  geocoder: 0
  geocoder_address: 0
  geocoder_field: 0
  geocoder_geofield: 0
  geofield: 0
  google_tag: 0
  help: 0
  helpers: 0
  history: 0
  image: 0
  image_captcha: 0
  image_effects: 0
  imagemagick: 0
  imperva_cache_purger: 0
  inline_entity_form: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  jsonapi: 0
  jsonapi_extras: 0
  language: 0
  layout_discovery: 0
  link: 0
  locale: 0
  mailsystem: 0
  media: 0
  media_entity_browser_media_library: 0
  media_library: 0
  menu_ui: 0
  metatag: 0
  migrate: 0
  migrate_plus: 0
  migrate_tools: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  paragraphs_library: 0
  paragraphs_type_permissions: 0
  password_policy_character_types: 0
  password_policy_length: 0
  path: 0
  path_alias: 0
  path_redirect_import: 0
  pdfpreview: 0
  purge: 0
  purge_queuer_coretags: 0
  purge_ui: 0
  quick_node_clone: 0
  quickedit: 0
  rabbit_hole: 0
  rdf: 0
  recaptcha: 0
  redirect: 0
  redirect_domain: 0
  rh_node: 0
  rh_taxonomy: 0
  rh_user: 0
  search: 0
  search_api: 0
  search_api_db: 0
  search_api_solr: 0
  serialization: 0
  sfweb2lead_webform: 0
  shortcut: 0
  sophron: 0
  swiftmailer: 0
  system: 0
  tamper: 0
  taxonomy: 0
  taxonomy_access_fix: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  tracker: 0
  twig_tweak: 0
  update: 0
  upgrade_status: 0
  user: 0
  video_embed_field: 0
  views_taxonomy_term_name_into_id: 0
  views_ui: 0
  webform: 0
  webform_node: 0
  webform_ui: 0
  workflows: 0
  menu_link_content: 1
  pathauto: 1
  content_translation: 10
  password_policy: 10
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  bartik: 0
  seven: 0
  atg: 0
  cleco: 0
profile: standard
