_core:
  default_config_hash: D0RcOA_aIiwSPXOZSHQOTm5FXzziEsJHdfXGaF4nhIQ
local_task_enabled_entity_types:
  - paragraphs_library_item
track_enabled_source_entity_types:
  - block_content
  - comment
  - contact_message
  - media
  - node
  - paragraphs_library_item
  - shortcut
  - taxonomy_term
  - menu_link_content
  - paragraph
track_enabled_target_entity_types:
  - block_content
  - comment
  - contact_message
  - media
  - node
  - paragraphs_library_item
  - shortcut
  - taxonomy_term
  - menu_link_content
  - paragraph
track_enabled_plugins:
  - block_field
  - dynamic_entity_reference
  - entity_embed
  - entity_reference
  - html_link
  - link
  - linkit
track_enabled_base_fields: false
site_domains: {  }
edit_warning_message_entity_types:
  - paragraphs_library_item
delete_warning_message_entity_types:
  - paragraphs_library_item
usage_controller_items_per_page: 25
