entity_type_groups:
  node:
    about:
      basic: basic
      advanced: advanced
    article:
      basic: basic
      advanced: advanced
    contact:
      basic: basic
      advanced: advanced
    distributors:
      basic: basic
      advanced: advanced
    downloads:
      basic: basic
      advanced: advanced
    geo_directory:
      basic: basic
    home:
      basic: basic
      advanced: advanced
    page:
      basic: basic
      advanced: advanced
    products_landing:
      basic: basic
      advanced: advanced
    service_support:
      basic: basic
      advanced: advanced
    solutions:
      basic: basic
      advanced: advanced
    solutions_landing:
      basic: basic
      advanced: advanced
