step_es_indices: null
step_file:
  - '129'
step_es_hosts: 'https://search-atg-tid3j5pwom3supbbmkm7djf3ki.us-east-2.es.amazonaws.com:443'
step_xml:
  - 162
step_xml_en:
  - '666'
step_xml_de:
  - '667'
step_xml_gb:
  - '668'
