_core:
  default_config_hash: 0dJfQivKgyEp-S8D6gSRTBbpRFApE3VkpltnPMBQ5OY
transport: smtp
smtp_host: smtp.atg.root
smtp_port: 25
smtp_encryption: '0'
sendmail_path: /usr/sbin/sendmail
sendmail_mode: bs
smtp_credential_provider: swiftmailer
smtp_credentials:
  swiftmailer:
    username: ''
    password: null
spool_directory: ''
