_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: a8355cff-50d7-4081-b779-0b93605af02d
name: Cleco
mail: no-reply@apextoolgroup.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/497
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
