warranty_sftp_host: '199.115.148.37'
warranty_sftp_username: 'ftpmagento'
warranty_sftp_password: 'UbgrBlA3'
warranty_sftp_root: '/Magento/WarrantyExport/Queue'
warranty_vendor_code: 'APEX-SAT-EMEA-POR'
warranty_sid_prepend: 'SAT-EMEA'
