ignored_config_entities:
  - 'block.block.custom_*'
  - 'sata_core.settings:warranty_highest_exported_sid'
  - 'acquia_connector.settings:spi.site_environment'
  - 'acquia_connector.settings:spi.site_uuid'
  - 'search_api.server.acquia_search_server:backend_config.connector_config'
  - 'webform.webform.*'
  - 'sata.settings:price_spider_hide'
  - 'sata.settings:price_spider_generic_key'
  - 'sata.settings:price_spider_product_key'
  - 'sata.settings:price_spider_country'
  - 'sata.settings:price_spider_language'
  - 'sata.settings:cookiebot_cbid'
  - 'sata.settings:logo_tagline*'
