features:
  node_user_picture: 1
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 0
  path: themes/custom/sata/favicons/favicon.ico
  mimetype: image/vnd.microsoft.icon
enable_w1_grid: 1
price_spider_hide: 1
price_spider_generic_key: ''
price_spider_product_key: ''
price_spider_country: ''
price_spider_language: ''
cookiebot_cbid: f12d9173-af9f-4af9-ab43-74bb59153770
logo_tagline:
  path: ''
  use_default: 0
  url: ''
