features:
  node_user_picture: 1
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 0
  path: themes/custom/sata/favicons/favicon.ico
  mimetype: image/vnd.microsoft.icon
enable_w1_grid: 1
price_spider_hide: 0
price_spider_generic_key: ''
price_spider_product_key: ''
price_spider_country: ''
price_spider_language: ''
logo_tagline:
  use_default: 1
  url: themes/custom/sata/icons/logo-tagline.svg
