label: 'Ablaufen des Passworts'
description: 'Aktivieren, falls der Nutzer sein Passwort zurücksetzen soll. Wenn das Passwort abgelaufen ist, wird dieses Feld automatisch per Cron angehakt.'
settings:
  on_label: 'Abgelaufenes Passwort'
  off_label: 'Nicht abgelaufenens Passwort'
