title: 'Reparaturen und Kalibrierung'
elements: |
  title:
    '#title': Titel
    '#options':
      Mrs.: Frau
      Mr.: Herr
  first_name:
    '#title': Vorname
  last_name:
    '#title': Nachname
  company:
    '#title': Firma
  address:
    '#title': Straße
  postal:
    '#title': PLZ
  city:
    '#title': Ort
  country:
    '#title': Land
  phone_number:
    '#title': Telefon
  email:
    '#title': E-Mail
  message:
    '#title': Nachricht
    '#placeholder': 'Achten Sie darauf, dass Sie die Modellnummer des jeweiligen Werkzeugs angeben.'
  opt_in:
    '#field_suffix': 'Ich möchte den Newsletter abonnieren. Die Abmeldung ist jederzeit möglich.'
  cleverreach_id:
    '#default_value': '228815'
  opt_in_form_id:
    '#default_value': '113578'
  language:
    '#default_value': de
  privacy_policy:
    '#markup': 'Hier geht es zu unserer <a href="/datenschutzinformation">Datenschutzerkl&auml;rung</a>.'
  actions:
    '#submit__label': 'Nachricht senden'
settings:
  confirmation_message: 'Vielen Dank für Ihr Interesse.<br>Wir werden uns schnellstmöglich mit Ihnen in Verbindung setzen.'
