title: 'Fordern Sie Produktinformationen an'
elements: |
  first_name:
    '#title': Vorname
  last_name:
    '#title': Nachname
  company:
    '#title': Firma
  address:
    '#title': Straße
  postal:
    '#title': PLZ
  city:
    '#title': Ort
  country:
    '#title': Land
  phone_number:
    '#title': Telefonnummer
  email:
    '#title': E-Mail
  message:
    '#title': Nachricht
    '#placeholder': 'Nennen Sie das Produkt oder die Produkte, für die Sie einen Vorführtermin vereinbaren möchten.'
  opt_in:
    '#field_suffix': 'Ich möchte den Newsletter abonnieren. Die Abmeldung ist jederzeit möglich.'
  cleverreach_id:
    '#default_value': '228791'
  language:
    '#default_value': de
  privacy_policy:
    '#markup': 'Hier geht es zu unserer <a href="/datenschutzinformation">Datenschutzerkl&auml;rung</a>.'
  actions:
    '#submit__label': 'Nachricht senden'
settings:
  confirmation_message: 'Vielen Dank für Ihr Interesse.<br>Wir werden uns schnellstmöglich mit Ihnen in Verbindung setzen.'
