elements: |
  title:
    '#title': Titel
    '#options':
      Mrs.: Frau
      Mr.: Herr
    '#empty_option': 'Titel auswählen...'
  last_name:
    '#title': Nachname
  email:
    '#title': E-Mail
  newsletter_language:
    '#title': 'Newsletter Sprache'
    '#options':
      en: Englisch
      de: Deutsch
    '#default_value':
      - de
  opt_in:
    '#description': 'Ich willige hiermit ein, den personalisierten Newsletter der Apex Tool Group GmbH, Industriestraße 1, 73463 Westhausen zu erhalten, um über Produktneuheiten und besondere Verkaufsaktionen/ Veranstaltungen hingewiesen zu werden. Der Widerruf ist jederzeit möglich, z.B. per E-Mail.'
  privacy_policy:
    '#markup': 'Weitere Informationen zur Datenverarbeitung finden Sie in unserer  <a href="/datenschutzinformation" target="_blank">Datenschutzerkl&auml;rung</a>.'
  cleverreach_id:
    '#default_value': '231251'
  opt_in_form_id:
    '#default_value': '138492'
  language:
    '#default_value': de
  actions:
    '#submit__label': Abonnieren
settings:
  confirmation_message: "<p><b>Vielen Dank für Ihr Interesse an unserem Newsletter.</b></p>\r\n<p>Um die Anmeldung abzuschließen, öffnen Sie bitte den Link in der E-Mail, die Sie schnellst möglichst erhalten werden.</p>"
