elements: |
  title:
    '#title': Anrede
    '#options':
      Mr.: Herr
      Mrs.: Frau
  first_name:
    '#title': Vorname
  last_name:
    '#title': Nachname
  email_address:
    '#title': E-Mail
  company:
    '#title': Firma
  zip_code:
    '#title': PLZ
  language:
    '#default_value': de
  actions:
    '#submit__label': 'Herunterladen Jetzt'
