elements: |
  title:
    '#title': Anrede
    '#options':
      Mrs.: Frau
      Mr.: Herr
  first_name:
    '#title': Vorname
  last_name:
    '#title': Nachname
  company:
    '#title': Firma
  street:
    '#title': Straße
  zip_code:
    '#title': PLZ
  city:
    '#title': Ort
  country:
    '#title': Land
  phone:
    '#title': Telefon
    '#placeholder': '__ ____ ____'
  email:
    '#title': E-Mail
  privacy_policy:
    '#markup': 'Hier geht es zu unserer <a href="/datenschutzinformation" target="_blank">Datenschutzerklärung</a>.'
  cleverreach_id:
    '#default_value': '231060'
  language:
    '#default_value': de
  actions:
    '#submit__label': Absenden
title: 'Produktvorführung Vereinbaren (Enhanced Products)'
settings:
  confirmation_message: 'Vielen Dank für Ihr Interesse.<br>Wir werden uns schnellstmöglich mit Ihnen in Verbindung setzen.'
