<?php

/**
 * @file
 * Hook implementations of commerce_us_custom_tax module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter() for commerce_checkout_flow_multistep_default.
 */
function commerce_us_custom_tax_form_alter(array &$form, FormStateInterface &$form_state, $form_id) {
  if (($form_id == 'commerce_checkout_flow_multistep_default' && $form['#step_id'] == 'order_information') || $form_id == 'profile_customer_edit_form' || $form_id == 'profile_customer_add_form') {
    $form['#attached']['library'][] = 'commerce_us_custom_tax/ajax_alter_address';
  }
}
