_core:
  default_config_hash: l58O_yEXSo-SeJi19LXdzTU1tNJG3lmnIhCitRkM1tk
langcode: en
uuid: bc1f9a6f-53f6-41d3-acc9-62f13e1b1417
name: Campbell
mail: campbell@apex.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/12
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
